### ISSUE TITLE
Import data from Excel

### ISSUE THREAD

**Issue by FrancoisPog** [ValFraNath/glowing-octo-guacamole#99]
Create a system to import data from an Excel file to the database.

- [x] Parse a CSV file into a `JSON` exploitable object (#102 )
- [x] Checks the data validity (#174)
- [x] Insert data in database (#117)
- [x] Configure the server route to receive the request with the file to import (#180)
- [ ] Create the client view allowing to send the csv files (#182 )
